version: "3"

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  app:
    container_name: app
    image: golang:latest
    depends_on:
      - redis

volumes:
  redis_data:
